markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: "https://l1f7.github.io/simplexmobility-styleguide"

sass:
  sass_dir: ../
  style: compressed

github:
  repo: https://github.com/l1f7/simplexmobility-styleguide
